spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:mysql://mysql:3306/identity_service
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  server:
    port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: identity-service
  tracing:
    sampling:
      probability: 1.0

loki:
  url: http://loki:3100/loki/api/v1/push

jwt:
  signerKey: "YCfb/2CrP/ogkgDu11sl5beiECqAHdT1uKyJufhAu9jmYSFvibW9kNnpBpIidKic"
  valid-duration: 2 # in seconds
  refreshable-duration: 4 # in seconds