apiVersion: v1
kind: Service
metadata:
  name: aggregate-service
  namespace: microservices
  labels:
    app: aggregate-service
spec:
  selector:
    app: aggregate-service
  ports:
  - name: http
    port: 5050
    targetPort: 5050
  type: NodePort