apiVersion: v1
kind: Service
metadata:
  name: friend-service
  namespace: microservices
  labels:
    app: friend-service
spec:
  selector:
    app: friend-service
  ports:
  - name: grpc
    port: 6060
    targetPort: 6060
  type: ClusterIP