apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: microservices
spec:
  selector:
    app: user-service
  ports:
  - name: http
    port: 4040
    targetPort: 4040
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: friend-service
  namespace: microservices
spec:
  selector:
    app: friend-service
  ports:
  - name: grpc
    port: 6060
    targetPort: 6060
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: aggregate-service
  namespace: microservices
spec:
  selector:
    app: aggregate-service
  ports:
  - name: http
    port: 5050
    targetPort: 5050
  type: NodePort